//The Project Euler Problem Two states that:
//
//    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//    Find the sum of all the even-valued terms in the sequence which do not exceed four million.

//The solution in Objective-C is:

    #import

    int main (int argc, const char *argv[]){

    	int x = 1;

   	int y = 2;

    	int z = 0;

    	int adder = 0;

    	while(y &lt; 4000000){

	    	if (y%2==0){

    			adder = adder + y;

    			NSLog(@"Current fibonacci number is %d", y);

    		}

    		z=y;

    		y=y+x;

    		x=z;

    	}

    	NSLog(@"The sum of all the even-valued terms in the sequence which do not exceed four million is %d", adder);

    }

//With the numerical value of the solution as:
//
//    4613732